version: '3'
services:
  redis-master:
    container_name: "redis-master"
    image: redis:6-alpine
    command: redis-server
    ports:
      - "6379:6379"

  redis-slave1:
    container_name: "redis-slave1"
    image: redis:6-alpine
    ports:
      - "6380:6379"
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master

  redis-slave2:
    container_name: "redis-slave2"
    image: redis:6-alpine
    ports:
      - "6381:6379"
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master

  envoy:
    image: envoyproxy/envoy-dev:latest
    ports:
      - "6000:6000"
      - "6001:6001"
    command: envoy -c /etc/envoy.yaml
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

