version: '3'
services:
  redis-master:
    container_name: "redis-master"
    image: redis:6-alpine
    command: redis-server --requirepass foobared
    ports:
      - "6379:6379"

  envoy:
    image: envoyproxy/envoy-dev:latest
    ports:
      - "6000:6000"
    command: envoy -c /etc/envoy.yaml
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

